name: "Messing with JSON"

on:
  workflow_dispatch:
    inputs:
      workload:
        required: true
        type: choice
        description: "The workload to use"
        options:
          - test1
          - test2
          - test3

jobs:
  get_env_vars:
    name: See the runner env vars
    runs-on: macos-12
    steps:
      - name: Get environment variables
        id: get_env_vars
        run: |
          echo "JAVA_HOME_17_X64=$JAVA_HOME_17_X64"
          echo "CHROMEWEBDRIVER=$CHROMEWEBDRIVER"